# Generated by Django 6.0 on 2025-12-06 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Video",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("esporte", models.CharField(max_length=50)),
                ("regiao", models.CharField(max_length=50)),
                ("descricao", models.TextField()),
                ("arquivo", models.FileField(upload_to="videos/")),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
