# Generated by Django 6.0 on 2025-12-06 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="likes",
            field=models.IntegerField(default=0),
        ),
    ]
