# Generated by Django 6.0 on 2025-12-07 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_video_likes"),
    ]

    operations = [
        migrations.CreateModel(
            name="Agente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("senha", models.CharField(max_length=128)),
                ("area_atuacao", models.CharField(max_length=100)),
                ("regiao", models.CharField(max_length=50)),
                ("descricao", models.TextField(blank=True, null=True)),
                (
                    "foto",
                    models.ImageField(
                        blank=True, null=True, upload_to="fotos_agentes/"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Atleta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("senha", models.CharField(max_length=128)),
                ("modalidade", models.CharField(max_length=100)),
                ("regiao", models.CharField(max_length=50)),
                (
                    "foto",
                    models.ImageField(
                        blank=True, null=True, upload_to="fotos_atletas/"
                    ),
                ),
            ],
        ),
    ]
