# Generated by Django 6.0 on 2025-12-11 23:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_mensagem"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="video",
            name="likes",
        ),
        migrations.CreateModel(
            name="Like",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("usuario_tipo", models.CharField(max_length=20)),
                ("usuario_id", models.IntegerField()),
                (
                    "video",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="likes",
                        to="main.video",
                    ),
                ),
            ],
            options={
                "unique_together": {("video", "usuario_tipo", "usuario_id")},
            },
        ),
    ]
