# Generated by Django 6.0 on 2025-12-11 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_remove_video_likes_like"),
    ]

    operations = [
        migrations.CreateModel(
            name="Conversa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("usuario1_tipo", models.CharField(max_length=20)),
                ("usuario1_id", models.IntegerField()),
                ("usuario2_tipo", models.CharField(max_length=20)),
                ("usuario2_id", models.IntegerField()),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "unique_together": {
                    ("usuario1_tipo", "usuario1_id", "usuario2_tipo", "usuario2_id")
                },
            },
        ),
    ]
