# Generated by Django 6.0 on 2025-12-11 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_conversa"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Conversa",
        ),
    ]
